Repository RaaLabs/TSIClient, pull requests merged in 2020-09, with the labels that each got.

#40 Client restructuring
  TSIClient/TSIClient.py
  TSIClient/authorization/authorization_api.py
  TSIClient/common/common_funcs.py
  TSIClient/environment/environment_api.py
  TSIClient/hierarchies/hierarchies_api.py
  TSIClient/instances/instances_api.py
  TSIClient/query/query_api.py
  TSIClient/types/types_api.py
  tests/conftest.py
  tests/test_tsiclient.py
Labels: breaking change

#42 Test setup
  README.md
  tests/authorization/test_authorization_api.py
  tests/conftest.py
  tests/environment/test_environment_api.py
  tests/hierarchies/test_hierarchies_api.py
  tests/instances/test_instances_api.py
  tests/query/test_query_api.py
  tests/test_tsiclient.py
  tests/types/test_types_api.py
Labels: enhancement

#43 Update docs for readthedocs
  TSIClient/authorization/__init__.py
  TSIClient/common/__init__.py
  TSIClient/environment/__init__.py
  TSIClient/environment/environment_api.py
  TSIClient/hierarchies/__init__.py
  TSIClient/hierarchies/hierarchies_api.py
  TSIClient/instances/__init__.py
  TSIClient/instances/instances_api.py
  TSIClient/query/__init__.py
  TSIClient/query/query_api.py
  TSIClient/types/__init__.py
  docs/source/_autogen/TSIClient.authorization.authorization_api.rst
  docs/source/_autogen/TSIClient.authorization.rst
  docs/source/_autogen/TSIClient.common.common_funcs.rst
  docs/source/_autogen/TSIClient.common.rst
  docs/source/_autogen/TSIClient.environment.environment_api.rst
  docs/source/_autogen/TSIClient.environment.rst
  docs/source/_autogen/TSIClient.hierarchies.hierarchies_api.rst
  docs/source/_autogen/TSIClient.hierarchies.rst
  docs/source/_autogen/TSIClient.instances.instances_api.rst
  docs/source/_autogen/TSIClient.instances.rst
  docs/source/_autogen/TSIClient.query.query_api.rst
  docs/source/_autogen/TSIClient.query.rst
  docs/source/_autogen/TSIClient.rst
  docs/source/_autogen/TSIClient.types.rst
  docs/source/_autogen/TSIClient.types.types_api.rst
  docs/source/developer.rst
Labels: documentation

#52 Update userguide to version 2.0.0.
  TSIClient/TSIClient.py
  TSIClient/instances/instances_api.py
  TSIClient/types/types_api.py
  docs/source/userguide.rst
  tests/authorization/test_authorization_api.py
  tests/environment/test_environment_api.py
  tests/query/test_query_api.py
  tests/test_tsiclient.py
Labels: documentation

#50 Fixed types (scaling) when querying data.
  TSIClient/query/query_api.py
Labels: Patch
